### ISSUE TITLE
Which sensors are supported? 

### ISSUE THREAD

**Issue by tim-fan** [inomuh/indoor_localization#1]
Hi there, this looks like an interesting package!
The readme mentions that the algorithm is sensor independent - can you provide some specific examples of sensors that can be used with this package? And do these sensors have drivers available to provide the required anchor scan messages?

**Comment by tim-fan** [comment]
Update: 
I've noticed from the ROS tutorial page, that this package appears to target UWB systems
http://wiki.ros.org/indoor_localization/Tutorials

The tutorial covers writing a UWB driver to publish AnchorScans.

Are there any existing drivers available for publishing these messages? Which particular UWB systems are supported?

**Comment by elcingencturk** [comment]
The important thing in here is that UWB signals from the anchors are used by the tag (which is located on an AGV or etc.) and the TDOA values are calculated in here. After that the resulting TDOA values are published through the AnchorScan message. For this reason the algorithm is sensor independent. 

During the implementation of our system, data coming from the tag is read from serial port and published. I've been upload an example driver package in here: [https://github.com/inomuh/uwb_hardware_driver](url). You should write your own driver and this is the our driver's source code. 

Also, you can see the implementation of the system in here: [https://youtu.be/fiOq8mJMCQg](url)

If you have anything else to worry about, you can always ask me here.

**Comment by tim-fan** [comment]
Ok great, thanks for the clarification!
