### ISSUE TITLE
Can we see an actual demo ? 

### ISSUE THREAD

**Issue by jediofgever** [inomuh/indoor_localization#2]
Hi, 
Thanks for the interesting work. I walked through readme and had a general overview of the project. But I cannot see a demo or tutorial of the project in action. Is this still a work in progress ?

**Comment by elcingencturk** [comment]
Hi, 
You can reach the tutorial of this work from this link: http://wiki.ros.org/indoor_localization/Tutorials
Also the demo of the work is realized in a laboratory environment. Here is the video of demo: https://youtu.be/fiOq8mJMCQg 
Dtails about the work in: http://wiki.ros.org/indoor_localization

**Comment by jediofgever** [comment]
Thanks a lot for the info. 
I am trying to understand what are the possible advantages of this approach over the existing ones, say `robot_localization`.
